github: [metadata]
theme: jekyll-theme-hacker
title: jekotia.net
description: Hobbyist EE & Programming
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from